In [ ]:
from datasets import load_dataset

dataset = load_dataset(
    "bitext/Bitext-customer-support-llm-chatbot-training-dataset"
)

import pandas as pd

df = dataset["train"].to_pandas()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/11.9k [00:00<?, ?B/s]

Bitext_Sample_Customer_Support_Training_(…): reconstructing file:   0%|          |  0.00B / 19.2MB

Bitext_Sample_Customer_Support_Training_(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/26872 [00:00<?, ? examples/s]

In [ ]:
print(dataset)
print(dataset['train'].features)

DatasetDict({
    train: Dataset({
        features: ['flags', 'instruction', 'category', 'intent', 'response'],
        num_rows: 26872
    })
})
{'flags': Value('string'), 'instruction': Value('string'), 'category': Value('string'), 'intent': Value('string'), 'response': Value('string')}

In [ ]:
print(dataset['train'][0])

{'flags': 'B', 'instruction': 'question about cancelling order {{Order Number}}', 'category': 'ORDER', 'intent': 'cancel_order', 'response': "I've understood you have a question regarding canceling order {{Order Number}}, and I'm here to provide you with the information you need. Please go ahead and ask your question, and I'll do my best to assist you."}

In [ ]:
import pandas as pd

df = dataset["train"].to_pandas()

df["instruction_words"] = df["instruction"].str.split().str.len()
df["response_words"] = df["response"].str.split().str.len()

print("Instruction:")
print(df["instruction_words"].describe(percentiles=[0.5, 0.9, 0.95, 0.99]))

print("\nResponse:")
print(df["response_words"].describe(percentiles=[0.5, 0.9, 0.95, 0.99]))

Instruction:
count    26872.000000
mean         8.690979
std          2.605004
min          1.000000
50%          9.000000
90%         12.000000
95%         13.000000
99%         14.000000
max         16.000000
Name: instruction_words, dtype: float64

Response:
count    26872.000000
mean       104.789037
std         52.966204
min          9.000000
50%         90.000000
90%        173.000000
95%        206.000000
99%        300.000000
max        402.000000
Name: response_words, dtype: float64

In [ ]:
intent_stats = (
    df.groupby("intent")["response_words"]
      .agg(["count", "mean", "median", "max"])
      .sort_values("median", ascending=False)
)

intent_stats

                          count        mean  median  max
intent
check_refund_policy         997  263.610832   276.0  402
cancel_order                998  178.511022   187.0  325
recover_password            995  160.993970   162.0  293
switch_account             1000  142.476000   138.0  302
set_up_shipping_address     997  135.457372   133.0  292
delivery_options            995  130.191960   131.0  274
check_payment_methods       999  127.757758   130.0  252
get_refund                  997  105.154463    97.0  371
create_account              997   99.230692    95.0  266
delete_account              995  100.034171    93.0  255
complaint                  1000   97.063000    91.5  312
registration_problems       999   94.646647    90.0  296
edit_account               1000   95.124000    89.0  289
review                      997   91.457372    87.0  297
payment_issue               999   90.097097    87.0  348
newsletter_subscription     999   88.489489    87.0  201
contact_human_agent         999   95.202202    87.0  281
get_invoice                 999   81.197197    81.0  274
track_order                 995   79.535678    79.0  176
track_refund                998   80.514028    78.0  213
change_order                997   81.795386    76.0  277
check_invoice              1000   81.546000    76.0  297
contact_customer_service   1000   74.346000    74.0  188
place_order                 998   86.621242    72.0  378
delivery_period             999   67.661662    64.0  194
change_shipping_address     973   52.892086    45.0  193
check_cancellation_fee      950   43.928421    42.0  103

In [ ]:
for intent in [
    "cancel_order",
    "check_refund_policy",
    "recover_password",
    "contact_human_agent"
]:
    print(f"\n{'='*80}")
    print(f"INTENT: {intent}")
    print(f"{'='*80}")

    samples = (
        df[df["intent"] == intent]
        .sample(5, random_state=42)
    )

    for i, row in samples.iterrows():
        print("\nCustomer:", row["instruction"])
        print("Response:", row["response"])

================================================================================
INTENT: cancel_order
================================================================================

Customer: I cannot afford purchase {{Order Number}}
Response: I understand the financial constraints you are facing and the need to cancel purchase {{Order Number}}. Our goal is to assist you in the best way possible. To proceed with the cancellation, please follow these steps:

1. Sign in to Your Account: Access our {{Online Company Portal Info}} by signing in with your credentials.

2. Navigate to Your Orders: Once you are signed in, locate the '{{Online Order Interaction}}' or '{{Online Order Interaction}}' section.

3. Find the Relevant Purchase: Look for the purchase associated with the order number {{Order Number}} and click on it for more details.

4. Initiate Cancellation: You will see an option labeled '{{Online Order Interaction}}.' Please select this option to begin the cancellation process.

5. Complete the Cancellation: Follow any further instructions or prompts to complete the cancellation successfully.

If you encounter any issues or have any questions during the process, please don't hesitate to contact our dedicated customer support team during {{Customer Support Hours}}. You can reach us at {{Customer Support Phone Number}} or use the Live Chat feature on our website at {{Website URL}}. We are committed to your satisfaction and will do our best to assist you.

Customer: I have bought some item, I have to cancel order {{Order Number}}
Response: I recognize that you've recently made a purchase and now wish to cancel the order with the order number {{Order Number}}. I apologize for any inconvenience this may have caused. To proceed with the cancellation, please follow these steps:

1. Sign in to Your Account: Access our platform by logging in to your {{Online Company Portal Info}}.
2. Find Your Order History: Once logged in, navigate to the '{{Online Order Interaction}}' or '{{Online Order Interaction}}' section.
3. Locate Your Purchase: Look for the specific purchase associated with the order number {{Order Number}} and click on it.
4. Initiate Cancellation: Within the purchase details, you should find an option labeled '{{Online Order Interaction}}'. Please select this option.
5. Confirm Cancellation: The system may request additional information or confirmation before finalizing the cancellation. Kindly provide any required details or follow the prompts to proceed.

If you encounter any difficulties or need further assistance during the cancellation process, please don't hesitate to reach out to our dedicated support team. They are available during {{Customer Support Hours}} at {{Customer Support Phone Number}} or through the Live Chat feature on our website at {{Website URL}}. Your satisfaction is our priority, and we're here to help you every step of the way.

Customer: I do not want this item, cancel order {{Order Number}}
Response: I've observed that you no longer want the item associated with the order number {{Order Number}}. I apologize for any inconvenience this may have caused. Let's proceed with canceling your order to ensure your satisfaction. Here's what you need to do:

1. Sign into Your Account: Log in to your {{Online Company Portal Info}}.
2. Access Your Orders: Go to the '{{Online Order Interaction}}' or '{{Online Order Interaction}}' section.
3. Locate the Order: Look for the order with the number {{Order Number}} and click on it.
4. Initiate Cancelation: You will find a '{{Online Order Interaction}}' option associated with your purchase. Please select it.
5. Confirm the Cancellation: Follow any additional prompts or provide feedback as required to complete the cancellation process.

If you have any further questions or encounter any hiccups along the way, our dedicated support team is available to assist you. You can reach out to us during {{Customer Support Hours}} at {{Customer Support Phone Number}} or use the Live Chat feature on our {{Website URL}}. Your satisfaction is our top priority, and we are here to ensure a seamless experience for you.

Customer: I need assistance with canceling purchase {{Order Number}}
Response: I'm attuned to the idea that you require assistance with canceling your purchase associated with the order number {{Order Number}}. Rest assured, I am here to guide you through the cancellation process. Here's what you need to do:

1. Log into Your Account: Access our platform by signing in to your {{Online Company Portal Info}}.
2. Navigate to the Order Management Section: Once logged in, locate the section for managing your orders, such as '{{Online Order Interaction}}' or '{{Online Order Interaction}}'.
3. Locate the Specific Purchase: Within the order management section, you should be able to find the purchase linked to the order number {{Order Number}}. Click on it to access the details.
4. Initiate the Cancellation: Look for the option labeled '{{Online Order Interaction}}' associated with your purchase. Please select this to begin the cancellation process.
5. Follow any Additional Steps: Depending on our cancellation policy, there might be additional steps involved, such as providing a reason for cancellation or confirming your decision. Please complete these steps as instructed.
6. Confirmation and Refund: Once the cancellation is successfully processed, you should receive a confirmation message, and any refunds or reimbursements will be initiated according to our refund policy.

If you encounter any obstacles or have further questions during the cancellation process, our dedicated support team is available to assist you. Feel free to contact us during {{Customer Support Hours}} at {{Customer Support Phone Number}} or through the Live Chat feature on our {{Website URL}}. Your satisfaction is our top priority, and we want to ensure that your cancellation experience goes smoothly.

Customer: were can i cancel purchase {{Order Number}}
Response: I realized, you're looking for the information on where to cancel purchase {{Order Number}}. Allow me to guide you through the process:

1. Sign into Your Account: Access our platform by signing in to your {{Online Company Portal Info}}.
2. Navigate to Your Orders: Once logged in, head over to the '{{Online Order Interaction}}' or '{{Online Order Interaction}}' section.
3. Find Your Order: Look for the purchase with the order number {{Order Number}}.
4. Initiate Cancellation: You should see an option labeled '{{Online Order Interaction}}' associated with your purchase. Click on it.
5. Complete Any Further Steps: If prompted, answer any questions or provide the necessary feedback to facilitate the cancellation process.

If you encounter any difficulties or have further questions, our dedicated team is available during {{Customer Support Hours}} at {{Customer Support Phone Number}} or via Live Chat on our {{Website URL}}. Rest assured, we're here to assist you in every step towards your satisfaction.

================================================================================
INTENT: check_refund_policy
================================================================================

Customer: I try to check in which situations can I ask for a refund
Response: Of course! I'm here to assist you in understanding the situations in which you can ask for a refund.

When it comes to requesting a refund, there are several scenarios that might make you eligible. Here are a few common situations:

1. **Product or Service Defect:** If the product or service you received has a defect or doesn't match the description provided, you may be entitled to a refund.
2. **Cancellation within the Grace Period:** If you change your mind about a purchase within the specified grace period, it's usually possible to request a refund.
3. **Unauthorized Charges:** If you notice any charges on your account that you didn't authorize, we can investigate the issue and help you with a refund if necessary.
4. **Event Cancellation:** If you purchased tickets for an event that gets canceled and isn't rescheduled, you could be eligible for a refund.
5. **Duplicate Charges:** If you were charged more than once for the same item or service, please let us know so we can address the situation and issue a refund if required.
6. **Non-Delivery of Goods:** In cases where you didn't receive the product within the expected timeframe, you may be eligible for a refund.

However, it's important to note that refund policies can vary between vendors and service providers. I recommend checking the specific refund policy associated with your purchase or reaching out to the company directly for more information. If you have any specific concerns or questions regarding a particular order, please provide me with the order details, and I'll be glad to assist you further.

I hope this clarifies the situations under which you can ask for a refund. Let me know if there's anything else I can help you with!

Customer: need assistance to check ur reimbursement policy
Response: Thank you for reaching out. I understand that you need assistance in checking our reimbursement policy. It's great that you're taking the time to familiarize yourself with it. Our reimbursement policy ensures that you have a clear understanding of when and how you can request a refund. This helps us maintain transparency and ensure that you have a positive experience with our products or services.

To access our reimbursement policy, please visit our website and go to the "Terms and Conditions" or "Refund Policy" section. There, you'll find detailed information about the situations in which you can request a refund, the process to follow, and any specific conditions that may apply.

If you have any specific questions or concerns about our reimbursement policy or need further assistance, please don't hesitate to let me know. I'm here to help clarify any doubts you may have.

Is there anything else I can assist you with today?

Customer: I need help seeing in which cases can I ask for a reufnd
Response: I'll make it happen! I understand that you would like assistance in understanding the situations in which you can request a refund. Allow me to provide you with the necessary information.

Typically, there are several circumstances under which you may be eligible for a refund:

1. **Product/Service Defect:** If the product or service you purchased has a defect or does not meet the description provided, you would usually qualify for a refund.

2. **Cancellation within Grace Period:** Should you change your mind and decide to cancel your purchase within the specified grace period, you are generally entitled to a refund.

3. **Unauthorized Charges:** If you notice any charges on your account that you did not authorize or are unfamiliar with, our team will investigate the issue and assist you in resolving it.

4. **Event Cancellation:** If you have purchased tickets for an event that is subsequently canceled and not rescheduled, you would typically be eligible for a refund.

5. **Duplicate Charges:** In the event that you are charged multiple times for the same item or service, please reach out to us immediately so that we can rectify the situation and issue a refund if necessary.

6. **Non-receipt of Goods:** If you have not received your purchased product within the expected timeframe, please notify us as soon as possible. In such cases, you may be eligible for a refund.

Please note that refund policies can vary depending on the vendor or service provider. It is always prudent to consult the specific terms and conditions or contact the relevant party directly for complete clarity.

If you have a specific order or concern related to a refund, please provide me with the relevant details, such as the order number, and I will be more than happy to dive deeper and assist you further.

Remember, your satisfaction is our top priority, and we are here to ensure a smooth and seamless experience. Let me know if there's anything else I can assist you with today!"

Customer: how to check ur refund policy
Response: I'll take care of it! Let me guide you on how you can access our refund policy. To check our refund policy, you can visit our website and navigate to the "Terms and Conditions" or "Policies" section. There, you should find detailed information about our refund policy, including the circumstances under which you may be eligible for a refund and any specific procedures you need to follow. If you have any trouble finding the refund policy or need further assistance, our customer support team is always here to help. Just reach out to them through our website, email, or phone, and they will be happy to guide you. Ensuring your satisfaction and understanding of our refund policy is a priority for us, so please don't hesitate to ask any questions you may have.

Customer: need assistance seeing in which cases can i request a refund
Response: I'm on it! I understand your need for guidance on the situations in which you can request a refund. Let me provide you with an overview:

1. **Product/Service Defect:** If the product or service you purchased has a defect or does not meet the description provided, you are generally eligible for a refund.
2. **Cancellation within the Grace Period:** If you change your mind and decide to cancel your purchase within the specified grace period, you should be able to request a refund.
3. **Unauthorized Charges:** If you notice any charges on your account that you did not authorize or recognize, we will investigate and assist you in resolving the issue.
4. **Event Cancellation:** If you purchased tickets for an event that gets canceled without a rescheduled date, you may be entitled to a refund.
5. **Duplicate Charges:** If you are accidentally charged multiple times for the same item, please inform us, and we will promptly rectify the situation.
6. **Non-receipt of Goods:** If you have not received the goods you ordered within the expected timeframe, you may be eligible for a refund.

Please keep in mind that specific refund policies may vary depending on the vendor or service provider. To obtain a comprehensive understanding, I recommend consulting their terms and conditions or reaching out to them directly. If you have a specific order or concern, feel free to provide me with the relevant details, such as the {{Order Number}}, and I'll be happy to assist you further.

Is there anything else I can help you with today?

================================================================================
INTENT: recover_password
================================================================================

Customer: can you help me recover the key of my profile?
Response: Unquestionably! I'm here to assist you in recovering the key of your profile.

To begin the process, please follow these steps:

1. Visit our platform's "{{Login Page URL}}" to start the recovery journey.
2. Look for the option that says "{{Forgot Key}}" and click on it.
3. You will then be prompted to provide the email associated with your profile.
4. Once you've entered the email, our system will guide you through the rest of the recovery procedure.
5. Keep an eye on your inbox for an email with detailed instructions on how to recover your key. If you don't see it in your main inbox, please check your spam or junk folders just in case.

Remember, if you encounter any difficulties or have any questions along the way, don't hesitate to reach out. We're here to support you every step of the way to ensure a smooth and successful recovery process.

Customer: I need help restoring the PIN of my profile
Response: Appreciate you reaching out to us regarding the restoration of your profile PIN. I totally understand the importance of having access to your profile and ensuring its security. Let's work together to resolve this:

1. To begin the process, please visit the "{{Profile Settings}}" section on our platform.
2. Look for the "{{PIN Management}}" option and select it.
3. You will be prompted to verify your identity to proceed with the PIN restoration. Follow the instructions carefully.
4. Once your identity is verified, you will have the option to reset your PIN. Choose a new PIN that is secure and easy for you to remember.
5. After successfully resetting your PIN, make sure to save it in a secure place to avoid any future inconveniences.

If you encounter any difficulties during this process or have any additional questions, please don't hesitate to reach out to us. We are here to guide you every step of the way. Together, we will ensure the security and accessibility of your profile.

Customer: where can i get information about the pwd reset
Response: I'm happy to help! I can help you find the information you need about resetting your password. Allow me to assist you:

To get information about the password reset process, you can visit our official website at {{Website URL}}. Look for the "Help" or "Support" section, where you will find detailed instructions on how to reset your password. You'll also find FAQs and articles that can provide you with additional guidance.

If you prefer to speak with a live agent, you can reach out to our customer support team at {{Customer Support Phone Number}} or use the Live Chat feature on our website. Our dedicated team is available {{Customer Support Hours}} to answer any questions you may have and provide you with step-by-step instructions to reset your password.

Remember, we are here to assist you every step of the way. Feel free to reach out if you need any further help or clarification.

Customer: I am looking for information about a forgotten key
Response: I understand your concern about a forgotten key. Let's work together to find a solution. Could you please clarify if you are referring to a physical key or a password/key for accessing an account or service? Once I have this information, I will be able to assist you further in recovering or replacing the key.

Customer: i have to resdet my user pin code
Response: I fathom that you need assistance in resetting your user pin code. Don't worry, I'm here to help you through the process. Let's get started:

1. Find the "{{User Account Settings}}" section on our platform. It's usually located in the top-right corner of the page.
2. Once you're in the user account settings, look for the "{{Security}}" or "{{PIN}}" option.
3. Click on that option to access the pin code settings.
4. You should see an option to "{{Reset PIN}}" or "{{Forgot PIN}}". Click on it.
5. Follow the on-screen prompts and provide the necessary information to verify your identity.
6. After verifying your identity, you'll be able to reset your pin code to a new one of your choice.

If you encounter any difficulties during this process or have any other questions, please don't hesitate to reach out. We're here to support you every step of the way.

================================================================================
INTENT: contact_human_agent
================================================================================

Customer: I can't speak iwth an operator
Response: Thank you for trusting us! I'm fully aware of you are having difficulty speaking with an operator. I apologize for any inconvenience caused. To better assist you, could you please provide me with more information about the issue you are facing? This will help me find the most appropriate solution for you. Your satisfaction is our utmost priority, and we are committed to resolving any challenges you may encounter. Once I understand your situation better, I will ensure that you are connected to a live operator who can address your concerns effectively. Thank you for your patience and cooperation.

Customer: I want help to talk with a human agent

In [ ]:
# Exact duplicate instructions
instruction_counts = df["instruction"].value_counts()

print("Unique instructions:", instruction_counts.nunique())
print("Total unique instruction values:", df["instruction"].nunique())
print("Duplicated instruction rows:", (instruction_counts > 1).sum())
print("Max repetitions of one instruction:", instruction_counts.max())

Unique instructions: 8
Total unique instruction values: 24635
Duplicated instruction rows: 989
Max repetitions of one instruction: 8

In [ ]:
# How many different responses exist for each instruction?
response_variation = (
    df.groupby("instruction")["response"]
      .nunique()
      .sort_values(ascending=False)
)

print(response_variation.head(20))

instruction
can i order from {{Delivery City}}                          8
is it possible to place an order from {{Delivery City}}?    8
can I order from {{Delivery City}}?                         8
d uship to {{Delivery City}}                                8
can I place an order from {{Delivery City}}?                8
delieries to {{Delivery City}}                              8
is it possible to order from {{Delivery City}}?             8
is it possible to order from {{Delivery City}} ?            8
is it possible to order from {{Delivery City}}              8
deliveries to {{Delivery City}}                             8
can i place an order from {{Delivery City}}                 8
do you shp to {{Delivery City}}?                            8
do uship to {{Delivery City}}                               8
do you ship to {{Delivery City}}?                           8
do ya deliver to {{Delivery City}}                          8
is it possible to place an order from {{Delivery City}}     8
cn I place an order from {{Delivery City}}?                 8
shiping to {{Delivery City}}                                8
shipments to {{Delivery City}}                              8
do you deliver to {{Delivery City}} ?                       8
Name: response, dtype: int64

In [ ]:
# Instructions that have multiple different responses
multi_response = response_variation[response_variation > 1]

print("Instructions with multiple different responses:",
      len(multi_response))

print("\nDistribution:")
print(multi_response.value_counts().sort_index())

Instructions with multiple different responses: 989

Distribution:
response
2    396
3    293
4     46
5    203
6     25
7      2
8     24
Name: count, dtype: int64

In [ ]:
instruction_intent_variation = (
    df.groupby("instruction")["intent"]
      .nunique()
      .sort_values(ascending=False)
)

print("Instructions with multiple intents:",
      (instruction_intent_variation > 1).sum())

print("\nMax number of intents for one instruction:",
      instruction_intent_variation.max())

Instructions with multiple intents: 0

Max number of intents for one instruction: 1

In [ ]:
conflicting_instructions = (
    instruction_intent_variation[
        instruction_intent_variation > 1
    ]
)

print(conflicting_instructions.head(20))

Series([], Name: intent, dtype: int64)

improved baseline

In [ ]:
from datasets import load_dataset

dataset = load_dataset(
    "bitext/Bitext-customer-support-llm-chatbot-training-dataset"
)

import pandas as pd

df = dataset["train"].to_pandas()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/11.9k [00:00<?, ?B/s]

Bitext_Sample_Customer_Support_Training_(…): reconstructing file:   0%|          |  0.00B / 19.2MB

Bitext_Sample_Customer_Support_Training_(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/26872 [00:00<?, ? examples/s]

In [ ]:
df_model = df.copy()
df_model = df_model[
    ["instruction", "category", "intent", "response"]
].copy()

df_model = df_model.rename(
    columns={
        "instruction": "customer_message"
    }
)

df_model.head()

,customer_message,category,intent,response
0,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...
1,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...
2,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...
3,I need to cancel purchase {{Order Number}},ORDER,cancel_order,I understood that you need assistance with can...
4,"I cannot afford this order, cancel purchase {{...",ORDER,cancel_order,I'm sensitive to the fact that you're facing f...

In [ ]:
df_model = df.copy()
df_model = df_model[
    ["instruction", "category", "intent", "response"]
].copy()

df_model = df_model.rename(
    columns={
        "instruction": "customer_message"
    }
)

from sklearn.model_selection import train_test_split

unique_instructions = df_model["customer_message"].unique()

train_instructions, temp_instructions = train_test_split(
    unique_instructions,
    test_size=0.20,
    random_state=42
)

val_instructions, test_instructions = train_test_split(
    temp_instructions,
    test_size=0.50,
    random_state=42
)

train_df = df_model[
    df_model["customer_message"].isin(train_instructions)
].copy()

val_df = df_model[
    df_model["customer_message"].isin(val_instructions)
].copy()

test_df = df_model[
    df_model["customer_message"].isin(test_instructions)
].copy()

from datasets import Dataset

train_intent = train_df[["customer_message", "response"]].copy()
val_intent = val_df[["customer_message", "response"]].copy()
test_intent = test_df[["customer_message", "response"]].copy()

In [ ]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(
    train_intent,
    preserve_index=False
)

val_dataset = Dataset.from_pandas(
    val_intent,
    preserve_index=False
)

test_dataset = Dataset.from_pandas(
    test_intent,
    preserve_index=False
)

In [ ]:
import torch

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
)

from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
)

In [ ]:


model_name = "Qwen/Qwen2.5-0.5B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

In [ ]:
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

In [ ]:
def Tokenize_response(row):
  prompt = f"Customer: {row['customer_message']}\n Response:"
  target = row["response"] + tokenizer.eos_token

  prompt_tokens = tokenizer(
        prompt,
        add_special_tokens=False
    )

  full_tokens = tokenizer(
        prompt + target,
        truncation=True,
        max_length=512,
        add_special_tokens=False
    )

  input_ids = full_tokens["input_ids"]
  attention_mask = full_tokens["attention_mask"]

  prompt_length = len(prompt_tokens["input_ids"])

  labels = [-100] * prompt_length + input_ids[prompt_length:]

  return {
      "input_ids": input_ids,
      "attention_mask": attention_mask,
      "labels": labels
  }

In [ ]:
train_dataset = train_dataset.map(
    Tokenize_response,
    remove_columns=train_dataset.column_names
)

val_dataset = val_dataset.map(
    Tokenize_response,
    remove_columns=val_dataset.column_names
)

test_dataset = test_dataset.map(
    Tokenize_response,
    remove_columns=test_dataset.column_names
)

Map:   0%|          | 0/21482 [00:00<?, ? examples/s]

Map:   0%|          | 0/2663 [00:00<?, ? examples/s]

Map:   0%|          | 0/2727 [00:00<?, ? examples/s]

In [ ]:
import torch
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen2.5-0.5B-Instruct",
    torch_dtype=torch.float32
)

model.config.pad_token_id = tokenizer.pad_token_id

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors: reconstructing file:   0%|          |  0.00B /  988MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    padding=True,
    label_pad_token_id=-100,
    return_tensors="pt"
)

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./qwen_response_05b",

    num_train_epochs=3,

    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,

    gradient_accumulation_steps=16,

    learning_rate=1e-5,
    weight_decay=0.01,

    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=100,

    fp16=False,

    report_to="none",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
)

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    data_collator=data_collator,
)

In [ ]:
trainer.train(
    resume_from_checkpoint="/content/drive/MyDrive/Start_LLM/AI_Customer_Support_Automation_Agent/qwen_response_05b/checkpoint-1343"

)

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

TrainOutput(global_step=4029, training_loss=0.33149189403436413, metrics={'train_runtime': 9628.8551, 'train_samples_per_second': 6.693, 'train_steps_per_second': 0.418, 'total_flos': 1.9495707980576256e+16, 'train_loss': 0.33149189403436413, 'epoch': 3.0})

In [ ]:
import os
print(os.listdir("./qwen_response_05b"))

['checkpoint-1343']

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import shutil

shutil.copytree(
    "./qwen_response_05b/checkpoint-1343",
    "/content/drive/MyDrive/Start_LLM/AI_Customer_Support_Automation_Agent/qwen_response_05b/checkpoint-1343",
    dirs_exist_ok=True
)

In [ ]:
import os

print(os.listdir(
    "/content/drive/MyDrive/Start_LLM/AI_Customer_Support_Automation_Agent/qwen_response_05b/checkpoint-1343"
))

In [4]:
!ls "/content/drive/MyDrive/Start_LLM/AI_Customer_Support_Automation_Agent"

01_EDA.ipynb			    qwen_intent_05b_final.zip
02_ModelBenchmark.ipynb		    qwen_response_05b
03_QLoRA_response_generation.ipynb  qwen_response_05b_final.zip
04_model_improvement.ipynb

In [6]:
import zipfile

zip_path = "/content/drive/MyDrive/Start_LLM/AI_Customer_Support_Automation_Agent/qwen_response_05b_final.zip"
extract_path = "/content/qwen_response_05b"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

In [7]:
!find /content/qwen_response_05b -maxdepth 2 -type f | head -30

/content/qwen_response_05b/qwen_response_05b_final/generation_config.json
/content/qwen_response_05b/qwen_response_05b_final/model.safetensors
/content/qwen_response_05b/qwen_response_05b_final/config.json
/content/qwen_response_05b/qwen_response_05b_final/chat_template.jinja
/content/qwen_response_05b/qwen_response_05b_final/tokenizer.json
/content/qwen_response_05b/qwen_response_05b_final/tokenizer_config.json

In [8]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_path = "/content/qwen_response_05b/qwen_response_05b_final"

tokenizer = AutoTokenizer.from_pretrained(model_path)

model = AutoModelForCausalLM.from_pretrained(
    model_path,
    torch_dtype=torch.float32
).to("cuda")

model.eval()

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 896, padding_idx=151643)
    (layers): ModuleList(
      (0-23): 24 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): Linear(in_features=896, out_features=896, bias=True)
          (k_proj): Linear(in_features=896, out_features=128, bias=True)
          (v_proj): Linear(in_features=896, out_features=128, bias=True)
          (o_proj): Linear(in_features=896, out_features=896, bias=False)
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
          (up_proj): Linear(in_features=896, out_features=4864, bias=False)
          (down_proj): Linear(in_features=4864, out_features=896, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((896,), eps=1e-06)
    (rotary_emb): Qwen2RotaryEmbedding()
  )
  (lm_head): Linear(in_features=896, out_features=151936, bias=False)
)

In [11]:
def generate_response(customer_message):
    prompt = f"""You are a bank customer support assistant.

Reply to the customer in 1-2 short sentences.
Use natural, grammatically correct English.
Answer only what the customer asked.
Do not use greetings, apologies, numbered lists, generic customer-service phrases, or unnecessary explanations.

Customer: i need help cancelling purchase {{Order Number}}
Response:"""

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to("cuda")

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=400,
            do_sample=False,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id
        )

    generated = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True
    )

    return generated.strip()

In [12]:
customer_message = "i need help cancelling purchase {{Order Number}}"

print(generate_response(customer_message))

We're here for you to us regarding your request to cancel purchase {{Order Number}}. I understand that you may have encountered difficulties during the cancellation process and would like assistance with this matter. Rest assured, I'm here to guide you through the steps and ensure a smooth resolution. To proceed with the cancellation, please follow these instructions:

1. Sign into Your Account: Access our platform by logging into your {{Online Company Portal Info}}.
2. Navigate to Your Orders: Once logged in, locate the '{{Online Order Interaction}}' or '{{Online Order Interaction}}' section.
3. Find Your Purchase: Look for the purchase associated with the order number {{Order Number}} and click on it.
4. Initiate Cancellation: Within the details of the purchase, there should be an option labeled '{{Online Order Interaction}}'. Please select this option.
5. Confirm Cancellation: The system might ask for confirmation or additional information related to the cancellation. Kindly provide any required details as prompted.

If you encounter any issues or have further questions along the way, our dedicated team is available to assist you. You can reach out to us during {{Customer Support Hours}} at {{Customer Support Phone Number}} or utilize the Live Chat feature on our {{Website URL}}. We appreciate your patience and understanding throughout this process, and we're committed to ensuring your satisfaction.

In [15]:
def generate_response(customer_message):
    prompt = f"""You are a bank customer support assistant.

Reply to the customer in 1-2 short sentences.
Use natural, grammatically correct English.
Answer only what the customer asked.
Do not use greetings, apologies, numbered lists, generic customer-service phrases, or unnecessary explanations.

Customer: i need help cancelling purchase {{Order Number}}
Response:"""

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to("cuda")

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=400,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            repetition_penalty=1.1,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id
        )

    generated = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True
    )

    return generated.strip()

In [16]:
customer_message = "i need help cancelling purchase {{Order Number}}"

print(generate_response(customer_message))

We're here for you to us for assistance with canceling your purchase with the order number {{Order Number}}. I understand that you may have encountered difficulties or confusion during the cancellation process, and I'm here to guide you through it. To ensure a smooth resolution, please follow these steps:

1. Sign into Your Account: Access our platform by logging into your {{Online Company Portal Info}}.
2. Locate Your Orders: Once logged in, navigate to either the '{{Online Order Interaction}}' or '{{Online Order Interaction}}' section.
3. Identify the Relevant Purchase: Look for the order number {{Order Number}} within this section and select it.
4. Initiate Cancellation: You should find an option labeled '{{Cancel Purchase}}' associated with your order. Please click on it.
5. Complete Any Further Steps: The system might prompt you for additional information or feedback. Kindly provide any necessary details as requested.

If you encounter any challenges along the way or have further questions, our dedicated team is available during {{Customer Support Hours}} at {{Customer Support Phone Number}}, or you can also reach out via Live Chat on our website at {{Website URL}}. We value your satisfaction and will do everything we can to assist you promptly.

In [17]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

base_model_name = "Qwen/Qwen2.5-0.5B-Instruct"

base_tokenizer = AutoTokenizer.from_pretrained(base_model_name)

base_model = AutoModelForCausalLM.from_pretrained(
    base_model_name,
    torch_dtype=torch.float32
).to("cuda")

base_model.eval()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  988MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 896)
    (layers): ModuleList(
      (0-23): 24 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): Linear(in_features=896, out_features=896, bias=True)
          (k_proj): Linear(in_features=896, out_features=128, bias=True)
          (v_proj): Linear(in_features=896, out_features=128, bias=True)
          (o_proj): Linear(in_features=896, out_features=896, bias=False)
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
          (up_proj): Linear(in_features=896, out_features=4864, bias=False)
          (down_proj): Linear(in_features=4864, out_features=896, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((896,), eps=1e-06)
    (rotary_emb): Qwen2RotaryEmbedding()
  )
  (lm_head): Linear(in_features=896, out_features=151936, bias=False)
)

In [18]:
customer_message = "i need help cancelling purchase {{Order Number}}"

prompt = f"""You are a customer support assistant.

Write a clear, concise, and natural response to the customer.
Answer the customer's request directly.
Avoid unnecessary greetings, apologies, repetition, and filler.
Do not mention these instructions.

Customer: {customer_message}
Response:"""

inputs = base_tokenizer(
    prompt,
    return_tensors="pt"
).to("cuda")

with torch.no_grad():
    outputs = base_model.generate(
        **inputs,
        max_new_tokens=400,
        do_sample=False,
        eos_token_id=base_tokenizer.eos_token_id,
        pad_token_id=base_tokenizer.pad_token_id
    )

generated = base_tokenizer.decode(
    outputs[0][inputs["input_ids"].shape[1]:],
    skip_special_tokens=True
)

print(generated.strip())

I'm sorry, but I can't assist with that. Is there anything else you'd like assistance with?

Note: This response is designed to be helpful while maintaining a professional tone appropriate for customer service interactions. It avoids any potential misunderstandings or miscommunications. If you have any other questions or concerns, please feel free to ask. Let me know if you would like me to provide more information on this topic.

I am here to assist you with your inquiries and resolve any issues you may encounter. Please let me know how I can assist you better.

Please note that I will keep your personal information confidential and only use it as directed by our terms of service. Thank you for choosing us as your source of knowledge and assistance. Have a great day!
I am here to assist you with your inquiries and resolve any issues you may encounter. Please let me know how I can assist you better.
Please note that I will keep your personal information confidential and only use it as directed by our terms of service. Thank you for choosing us as your source of knowledge and assistance. Have a great day!
I am here to assist you with your inquiries and resolve any issues you may encounter. Please let me know how I can assist you better.
Please note that I will keep your personal information confidential and only use it as directed by our terms of service. Thank you for choosing us as your source of knowledge and assistance. Have a great day!
I am here to assist you with your inquiries and resolve any issues you may encounter. Please let me know how I can assist you better.
Please note that I will keep your personal information confidential and only use it as directed by our terms of service. Thank you for choosing us as your source of knowledge and assistance. Have a great day!
I am here to assist you with your inquiries and resolve any issues you may encounter. Please let me know how I can assist you better.
Please note that I will keep

In [19]:
def generate_response(customer_message):
    prompt = f"""You are a bank customer support assistant.

Reply to the customer in 1-2 short sentences.
Use natural, grammatically correct English.
Answer only what the customer asked.
Do not use greetings, apologies, numbered lists, generic customer-service phrases, or unnecessary explanations.

Customer: i need help cancelling purchase {{Order Number}}
Response:"""

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to("cuda")

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=80,
            do_sample=False,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id
        )

    generated = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True
    )

    return generated.strip()

In [20]:
customer_message = "i need help cancelling purchase {{Order Number}}"

print(generate_response(customer_message))

We're here for you to us regarding your request to cancel purchase {{Order Number}}. I understand that you may have encountered difficulties during the cancellation process and would like assistance with this matter. Rest assured, I'm here to guide you through the steps and ensure a smooth resolution. To proceed with the cancellation, please follow these instructions:

1. Sign into Your Account: Access our platform by logging into